In [1]:
import warnings
import sys
warnings.simplefilter('ignore')

%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error

In [2]:
url = "resources/olg_solar_weather.csv"
fiveaxis = pd.read_csv(url)
fiveaxis = fiveaxis.fillna(0)
fiveaxis.head(100)

,date_time,power_delivered,energy_delivered,cumulative_energy,weather_description,clouds_all,temp_f,rain_1h,snow_1h,hour,day,month
0,2019-04-21 13:00:00,57444,14361,22937,broken clouds,75,71.420,0,0,13,21,4
1,2019-04-21 14:00:00,74580,18645,41582,sky is clear,1,72.644,0,0,14,21,4
2,2019-04-21 15:00:00,72024,18006,59588,broken clouds,75,72.572,0,0,15,21,4
3,2019-04-21 16:00:00,63552,15888,75476,broken clouds,75,71.456,0,0,16,21,4
4,2019-04-21 17:00:00,45996,11499,86975,sky is clear,1,68.756,0,0,17,21,4
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2019-04-25 12:00:00,58888,14722,391819,sky is clear,1,65.462,0,0,12,25,4
96,2019-04-25 13:00:00,78860,19715,411534,sky is clear,1,68.126,0,0,13,25,4
97,2019-04-25 14:00:00,86384,21596,433130,few clouds,20,69.530,0,0,14,25,4
98,2019-04-25 15:00:00,85476,21369,454499,scattered clouds,40,70.142,0,0,15,25,4
99,2019-04-25 16:00:00,76732,19183,473682,scattered clouds,40,70.520,0,0,16,25,4

In [3]:
col = list(fiveaxis.columns)
# print(col)

In [4]:
print(col)

['date_time', 'power_delivered', 'energy_delivered', 'cumulative_energy', 'weather_description', 'clouds_all', 'temp_f', 'rain_1h', 'snow_1h', 'hour', 'day', 'month']

In [5]:
# col = ['power_delivered', 'energy_delivered', 'cumulative_energy', 'clouds_all', 'temp_f', 'rain_1h', 'snow_1h', 'hour', 'day', 'month']

In [6]:
fiveaxis.describe()

,power_delivered,energy_delivered,cumulative_energy,clouds_all,temp_f,rain_1h,snow_1h,hour,day,month
count,2582.000000,2582.000000,2.582000e+03,2582.000000,2582.000000,2582.000000,2582.0,2582.000000,2582.000000,2582.000000
mean,20776.254067,5194.063517,6.476571e+06,41.489930,64.384651,0.156081,0.0,11.513555,16.010070,5.938420
std,27616.794372,6904.198593,3.916135e+06,37.201501,12.410933,0.531860,0.0,6.931810,9.225526,1.074016
min,0.000000,0.000000,2.293700e+04,0.000000,32.756000,0.000000,0.0,0.000000,1.000000,4.000000
25%,0.000000,0.000000,3.132624e+06,1.000000,55.602500,0.000000,0.0,5.250000,7.000000,5.000000
50%,5160.000000,1290.000000,6.581914e+06,40.000000,66.101000,0.000000,0.0,12.000000,16.000000,6.000000
75%,37377.000000,9344.250000,9.714027e+06,75.000000,73.094000,0.000000,0.0,18.000000,24.000000,7.000000
max,88816.000000,22204.000000,1.342216e+07,100.000000,92.138000,3.000000,0.0,23.000000,31.000000,8.000000

In [7]:
relationships = []
for i in col:
    try:
        for j in col:
            try:
                current = i
                newlist = j
                X = fiveaxis[newlist].values.reshape(-1,1)
                y = fiveaxis[current].values.reshape(-1,1)
                X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
                model = LogisticRegression()
                model.fit(X_train, y_train)
                print(f"{current}, {newlist} train: {model.score(X_train, y_train)}, test: {model.score(X_test, y_test)}")
            except ValueError:
                print(f"skip in j dimension {j}")
    except ValueError:
        print(f"skip in i dimension {i}")

skip in j dimension date_time
date_time, power_delivered train: 0.0005165289256198347, test: 0.0
date_time, energy_delivered train: 0.0010330578512396695, test: 0.0
date_time, cumulative_energy train: 0.0005165289256198347, test: 0.0
skip in j dimension weather_description
date_time, clouds_all train: 0.0010330578512396695, test: 0.0
date_time, temp_f train: 0.0005165289256198347, test: 0.0
date_time, rain_1h train: 0.0010330578512396695, test: 0.0
date_time, snow_1h train: 0.0005165289256198347, test: 0.0
date_time, hour train: 0.0010330578512396695, test: 0.0
date_time, day train: 0.0005165289256198347, test: 0.0
date_time, month train: 0.0005165289256198347, test: 0.0
skip in j dimension date_time
power_delivered, power_delivered train: 0.359504132231405, test: 0.32972136222910214
power_delivered, energy_delivered train: 0.36105371900826444, test: 0.32972136222910214
power_delivered, cumulative_energy train: 0.3584710743801653, test: 0.32972136222910214
skip in j dimension weather_description
power_delivered, clouds_all train: 0.3584710743801653, test: 0.32972136222910214
power_delivered, temp_f train: 0.3584710743801653, test: 0.32972136222910214
power_delivered, rain_1h train: 0.3584710743801653, test: 0.32972136222910214
power_delivered, snow_1h train: 0.3584710743801653, test: 0.32972136222910214
power_delivered, hour train: 0.3584710743801653, test: 0.32972136222910214
power_delivered, day train: 0.3584710743801653, test: 0.32972136222910214
power_delivered, month train: 0.3584710743801653, test: 0.32972136222910214
skip in j dimension date_time
energy_delivered, power_delivered train: 0.359504132231405, test: 0.32972136222910214
energy_delivered, energy_delivered train: 0.36105371900826444, test: 0.32972136222910214
energy_delivered, cumulative_energy train: 0.3584710743801653, test: 0.32972136222910214
skip in j dimension weather_description
energy_delivered, clouds_all train: 0.3584710743801653, test: 0.32972136222910214
energy_delivered, temp_f train: 0.3584710743801653, test: 0.32972136222910214
energy_delivered, rain_1h train: 0.3584710743801653, test: 0.32972136222910214
energy_delivered, snow_1h train: 0.3584710743801653, test: 0.32972136222910214
energy_delivered, hour train: 0.3584710743801653, test: 0.32972136222910214
energy_delivered, day train: 0.3584710743801653, test: 0.32972136222910214
energy_delivered, month train: 0.3584710743801653, test: 0.32972136222910214
skip in j dimension date_time
cumulative_energy, power_delivered train: 0.005165289256198347, test: 0.0
cumulative_energy, energy_delivered train: 0.005165289256198347, test: 0.0
cumulative_energy, cumulative_energy train: 0.005165289256198347, test: 0.0
skip in j dimension weather_description
cumulative_energy, clouds_all train: 0.01084710743801653, test: 0.0046439628482972135
cumulative_energy, temp_f train: 0.013946280991735538, test: 0.0030959752321981426
cumulative_energy, rain_1h train: 0.008264462809917356, test: 0.0015479876160990713
cumulative_energy, snow_1h train: 0.006198347107438017, test: 0.0015479876160990713
cumulative_energy, hour train: 0.005681818181818182, test: 0.0030959752321981426
cumulative_energy, day train: 0.007747933884297521, test: 0.0015479876160990713
cumulative_energy, month train: 0.01084710743801653, test: 0.0030959752321981426
skip in j dimension date_time
weather_description, power_delivered train: 0.21797520661157024, test: 0.2089783281733746
weather_description, energy_delivered train: 0.2143595041322314, test: 0.19659442724458204
weather_description, cumulative_energy train: 0.10537190082644628, test: 0.08513931888544891
skip in j dimension weather_description
weather_description, clouds_all train: 0.45609504132231404, test: 0.4179566563467492
weather_description, temp_f train: 0.24793388429752067, test: 0.24148606811145512
weather_description, rain_1h train: 0.28202479338842973, test: 0.29256965944272445
weather_description, snow_1h train: 0.20041322314049587, test: 0.19040247678018576
weather_description, hour train: 0.1740702479338843, test: 0.16253869969040247
weather_description, day train: 0.20041322314049587, test: 0.19040247678018576
weather_description, month train: 0.2980371900826446, test: 0.26625386996904027
skip in j dimension date_time
clouds_all, power_delivered train: 0.375, test: 0.33436532507739936
clouds_all, energy_delivered train: 0.3744834710743802, test: 0.33591331269349844
clouds_all, cumulative_energy train: 0.36518595041322316, test: 0.3328173374613003
skip in j dimension weather_description
clouds_all, clouds_all train: 0.9028925619834711, test: 0.8947368421052632
clouds_all, temp_f train: 0.38791322314049587, test: 0.3606811145510836
clouds_all, rain_1h train: 0.4271694214876033, test: 0.42105263157894735
clouds_all, snow_1h train: 0.36518595041322316, test: 0.3328173374613003
clouds_all, hour train: 0.32541322314049587, test: 0.28792569659442724
clouds_all, day train: 0.36518595041322316, test: 0.3328173374613003
clouds_all, month train: 0.36518595041322316, test: 0.3328173374613003
skip in j dimension date_time
skip in j dimension power_delivered
skip in j dimension energy_delivered
skip in j dimension cumulative_energy
skip in j dimension weather_description
skip in j dimension clouds_all
skip in j dimension temp_f
skip in j dimension rain_1h
skip in j dimension snow_1h
skip in j dimension hour
skip in j dimension day
skip in j dimension month
skip in j dimension date_time
rain_1h, power_delivered train: 0.8997933884297521, test: 0.8777089783281734
rain_1h, energy_delivered train: 0.8997933884297521, test: 0.8777089783281734
rain_1h, cumulative_energy train: 0.8997933884297521, test: 0.8777089783281734
skip in j dimension weather_description
rain_1h, clouds_all train: 0.8997933884297521, test: 0.8777089783281734
rain_1h, temp_f train: 0.8997933884297521, test: 0.8777089783281734
rain_1h, rain_1h train: 1.0, test: 1.0
rain_1h, snow_1h train: 0.8997933884297521, test: 0.8777089783281734
rain_1h, hour train: 0.8997933884297521, test: 0.8777089783281734
rain_1h, day train: 0.8997933884297521, test: 0.8777089783281734
rain_1h, month train: 0.8997933884297521, test: 0.8777089783281734
skip in j dimension date_time
skip in j dimension power_delivered
skip in j dimension energy_delivered
skip in j dimension cumulative_energy
skip in j dimension weather_description
skip in j dimension clouds_all
skip in j dimension temp_f
skip in j dimension rain_1h
skip in j dimension snow_1h
skip in j dimension hour
skip in j dimension day
skip in j dimension month
skip in j dimension date_time
hour, power_delivered train: 0.12861570247933884, test: 0.1021671826625387
hour, energy_delivered train: 0.1859504132231405, test: 0.15170278637770898
hour, cumulative_energy train: 0.04493801652892562, test: 0.032507739938080496
skip in j dimension weather_description
hour, clouds_all train: 0.06198347107438017, test: 0.043343653250773995
hour, temp_f train: 0.07076446280991736, test: 0.04643962848297214
hour, rain_1h train: 0.04700413223140496, test: 0.034055727554179564
hour, snow_1h train: 0.04493801652892562, test: 0.032507739938080496
hour, hour train: 0.38171487603305787, test: 0.3560371517027864
hour, day train: 0.04700413223140496, test: 0.02631578947368421
hour, month train: 0.04493801652892562, test: 0.030959752321981424
skip in j dimension date_time
day, power_delivered train: 0.03409090909090909, test: 0.02631578947368421
day, energy_delivered train: 0.04648760330578512, test: 0.03715170278637771
day, cumulative_energy train: 0.03770661157024793, test: 0.03560371517027864
skip in j dimension weather_description
day, clouds_all train: 0.05113636363636364, test: 0.04489164086687306
day, temp_f train: 0.0506198347107438, test: 0.03869969040247678
day, rain_1h train: 0.047520661157024795, test: 0.029411764705882353
day, snow_1h train: 0.040805785123966945, test: 0.02631578947368421
day, hour train: 0.04132231404958678, test: 0.02476780185758514
day, day train: 0.3290289256198347, test: 0.3142414860681115
day, month train: 0.0490702479338843, test: 0.03869969040247678
skip in j dimension date_time
month, power_delivered train: 0.30010330578512395, test: 0.29411764705882354
month, energy_delivered train: 0.3047520661157025, test: 0.29876160990712075

month, cumulative_energy train: 0.2902892561983471, test: 0.2801857585139319
skip in j dimension weather_description
month, clouds_all train: 0.31456611570247933, test: 0.3653250773993808
month, temp_f train: 0.5036157024793388, test: 0.5185758513931888
month, rain_1h train: 0.2964876033057851, test: 0.2894736842105263
month, snow_1h train: 0.2902892561983471, test: 0.2801857585139319
month, hour train: 0.29545454545454547, test: 0.2647058823529412
month, day train: 0.27479338842975204, test: 0.2894736842105263
month, month train: 0.8502066115702479, test: 0.868421052631579

In [8]:
# print(relationships)

In [9]:
# j = 0
# final = []
# for i in relationships:
#     current = i
# #     newlist = col
#     newlist = list(filter(lambda x: x != i, relationships))
# #     print(current)
# #     print(newlist)
# #     print(j)
#     j = j + 1
#     X = fiveaxis[newlist]
#     y = fiveaxis[current].values.reshape(-1,1)
#     X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
#     X_scaler = StandardScaler().fit(X_train)
#     y_scaler = StandardScaler().fit(y_train)
#     X_train_scaled = X_scaler.transform(X_train)
#     X_test_scaled = X_scaler.transform(X_test)
#     y_train_scaled = y_scaler.transform(y_train)
#     y_test_scaled = y_scaler.transform(y_test)
#     model = LinearRegression()
#     model.fit(X_train_scaled, y_train_scaled)
#     predictions = model.predict(X_test_scaled)
#     MSE = mean_squared_error(y_test_scaled, predictions)
#     r2 = model.score(X_test_scaled, y_test_scaled)
#     if MSE != 0 and r2 != 1.0:
#       if MSE <= .1 and r2 >= .85:
#         final.append(current)
#     print(f"{current}, MSE: {MSE}, R2: {r2}")
# print(final)

In [10]:
# import pandas as pd
# import requests
# import datetime as dt
# from pprint import pprint

In [11]:
# import pandas as pd
# import requests
# import datetime as dt
# from pprint import pprint
# url = "https://api.sunrise-sunset.org/json?lat=44.986656&lng=-93.258133&date="
# # date = dt.date.today()
# date = fiveaxis['date_time'][0]

# response = requests.get(f"{url}{date}").json()
# pprint(response['results'])
# pprint(response['results']['day_length'])
# pprint(response['results']['sunrise'])
# pprint(response['results']['sunset'])

In [12]:
# print(date)

In [13]:
# for i in fiveaxis['date_time']:
#     date = i
#     response = requests.get(f"{url}{date}").json()
#     daylength = response['results']['day_length'] 
#     print(daylength)
# #         fiveaxis = fiveaxis.append(daylength)
# #     #     fiveaxis = fiveaxis.append(pd.io.json.json_normalize(response['results']['sunrise']))
# #     #     fiveaxis = fiveaxis.append(pd.io.json.json_normalize(response['results']['sunset']))
# # fiveaxis.head()