In [7]:
import warnings
import sys
warnings.simplefilter('ignore')

%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsClassifier

In [11]:
url = "resources/mpls_solar_weather.csv"
fiveaxis = pd.read_csv(url)
fiveaxis = fiveaxis.fillna(0)
fiveaxis.head(100)

,date_time,power_delivered,energy_delivered,cumulative_energy,weather_description,clouds_all,temp_f,pressure,humidity,wind_speed,...,weather_main,hour,day_of_year,month,sin_day,cos_day,sin_hour,cos_hour,sin_month,cos_month
0,2017-05-26 15:00:00,445,111,111,sky is clear,1,76.316,1007,41,4,...,Clear,15,146,5,0.587785,-0.809017,-0.707107,-7.071068e-01,5.000000e-01,-0.866025
1,2017-05-26 16:00:00,2280,570,681,scattered clouds,40,77.000,1007,38,4,...,Clouds,16,146,5,0.587785,-0.809017,-0.866025,-5.000000e-01,5.000000e-01,-0.866025
2,2017-05-26 17:00:00,4186,1047,1728,scattered clouds,40,76.874,1006,36,5,...,Clouds,17,146,5,0.587785,-0.809017,-0.965926,-2.588190e-01,5.000000e-01,-0.866025
3,2017-05-26 18:00:00,4283,1071,2799,sky is clear,1,76.226,1007,36,4,...,Clear,18,146,5,0.587785,-0.809017,-1.000000,-1.836970e-16,5.000000e-01,-0.866025
4,2017-05-26 19:00:00,4043,1011,3809,sky is clear,1,74.642,1008,40,3,...,Clear,19,146,5,0.587785,-0.809017,-0.965926,2.588190e-01,5.000000e-01,-0.866025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2017-05-31 23:00:00,0,0,31103,sky is clear,1,50.864,1017,66,1,...,Clear,23,151,5,0.516062,-0.856551,-0.258819,9.659258e-01,5.000000e-01,-0.866025
96,2017-06-01 05:00:00,1,0,31104,sky is clear,1,42.800,1018,100,1,...,Clear,5,152,6,0.501242,-0.865307,0.965926,2.588190e-01,1.224647e-16,-1.000000
97,2017-06-01 06:00:00,75,19,31122,sky is clear,1,45.680,1019,87,1,...,Clear,6,152,6,0.501242,-0.865307,1.000000,6.123234e-17,1.224647e-16,-1.000000
98,2017-06-01 07:00:00,166,42,31164,sky is clear,5,52.232,1019,66,1,...,Clear,7,152,6,0.501242,-0.865307,0.965926,-2.588190e-01,1.224647e-16,-1.000000
99,2017-06-01 08:00:00,405,101,31265,sky is clear,5,60.224,1020,45,1,...,Clear,8,152,6,0.501242,-0.865307,0.866025,-5.000000e-01,1.224647e-16,-1.000000

In [9]:
col = list(fiveaxis.columns)
# print(col)

In [10]:
print(col)

['date_time', 'power_delivered', 'energy_delivered', 'cumulative_energy', 'weather_description', 'clouds_all', 'temp_f', 'pressure', 'humidity', 'wind_speed', 'wind_deg', 'rain_1h', 'snow_1h', 'weather_main', 'hour', 'day_of_year', 'month', 'sin_day', 'cos_day', 'sin_hour', 'cos_hour', 'sin_month', 'cos_month']

In [6]:
col = ['energy_delivered', 'cumulative_energy', 'clouds_all', 'temp_f', 'rain_1h', 'snow_1h', 'hour', 'day', 'month']

In [7]:
fiveaxis.describe()

,power_delivered,energy_delivered,cumulative_energy,clouds_all,temp_f,rain_1h,snow_1h,hour,day,month
count,2582.000000,2582.000000,2.582000e+03,2582.000000,2582.000000,2582.000000,2582.0,2582.000000,2582.000000,2582.000000
mean,20776.254067,5194.063517,6.476571e+06,41.489930,64.384651,0.156081,0.0,11.513555,16.010070,5.938420
std,27616.794372,6904.198593,3.916135e+06,37.201501,12.410933,0.531860,0.0,6.931810,9.225526,1.074016
min,0.000000,0.000000,2.293700e+04,0.000000,32.756000,0.000000,0.0,0.000000,1.000000,4.000000
25%,0.000000,0.000000,3.132624e+06,1.000000,55.602500,0.000000,0.0,5.250000,7.000000,5.000000
50%,5160.000000,1290.000000,6.581914e+06,40.000000,66.101000,0.000000,0.0,12.000000,16.000000,6.000000
75%,37377.000000,9344.250000,9.714027e+06,75.000000,73.094000,0.000000,0.0,18.000000,24.000000,7.000000
max,88816.000000,22204.000000,1.342216e+07,100.000000,92.138000,3.000000,0.0,23.000000,31.000000,8.000000

In [ ]:
y = fiveaxis['power_delivered']

In [21]:
# create bins for power_delivered
# labels = ['0', '<1000', '1000-2000', '2000-3000', '3000-4000', '4000-5000']
labels = range(0, 2)
power_bins = pd.cut(fiveaxis.power_delivered,
                         [-1, 0],
                         labels=labels)
power_bins.fillna(0, inplace=True)
power_bins.head()

0    0
1    0
2    0
3    0
4    0
Name: power_delivered, dtype: category
Categories (1, int64): [0]

In [17]:
for i in col:
    try:
        current = i
        newlist = list(filter(lambda x: x != i, col))
        X = fiveaxis[newlist]
        y = fiveaxis[current].values.reshape(-1,1)
        X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
#         X_scaler = StandardScaler().fit(X_train)
#         y_scaler = StandardScaler().fit(y_train)
#         X_train_scaled = X_scaler.transform(X_train)
#         X_test_scaled = X_scaler.transform(X_test)
#         y_train_scaled = y_scaler.transform(y_train)
#         y_test_scaled = y_scaler.transform(y_test)
        train_scores = []
        test_scores = []
        for k in col:
            try:
                knn = KNeighborsClassifier(n_neighbors=k)
                knn.fit(X_train, y_train)
                train_score = knn.score(X_train, y_train)
                test_score = knn.score(X_test, y_test)
                train_scores.append(train_score)
                test_scores.append(test_score)
                print(f"k: {i} _ {k}, Train/Test Score: {train_score:.3f}/{test_score:.3f}")
            except ValueError:
                print(f"{i} skip in k dimension {k} value")
            except TypeError:
                print(f"{i} skip in k dimension {k} type")
    except ValueError:
        print(f"skip in i dimension {i}")
    except ValueError:
        print(f"skip in i dimension {i}")

date_time skip in k dimension date_time value
date_time skip in k dimension power_delivered value
date_time skip in k dimension energy_delivered value
date_time skip in k dimension cumulative_energy value
date_time skip in k dimension weather_description value
date_time skip in k dimension clouds_all value
date_time skip in k dimension temp_f value
date_time skip in k dimension rain_1h value
date_time skip in k dimension snow_1h value
date_time skip in k dimension hour value
date_time skip in k dimension day value
date_time skip in k dimension month value
power_delivered skip in k dimension date_time value
power_delivered skip in k dimension power_delivered value
power_delivered skip in k dimension energy_delivered value
power_delivered skip in k dimension cumulative_energy value
power_delivered skip in k dimension weather_description value
power_delivered skip in k dimension clouds_all value
power_delivered skip in k dimension temp_f value
power_delivered skip in k dimension rain_1h value
power_delivered skip in k dimension snow_1h value
power_delivered skip in k dimension hour value
power_delivered skip in k dimension day value
power_delivered skip in k dimension month value
energy_delivered skip in k dimension date_time value
energy_delivered skip in k dimension power_delivered value
energy_delivered skip in k dimension energy_delivered value
energy_delivered skip in k dimension cumulative_energy value
energy_delivered skip in k dimension weather_description value
energy_delivered skip in k dimension clouds_all value
energy_delivered skip in k dimension temp_f value
energy_delivered skip in k dimension rain_1h value
energy_delivered skip in k dimension snow_1h value
energy_delivered skip in k dimension hour value
energy_delivered skip in k dimension day value
energy_delivered skip in k dimension month value
cumulative_energy skip in k dimension date_time value
cumulative_energy skip in k dimension power_delivered value
cumulative_energy skip in k dimension energy_delivered value
cumulative_energy skip in k dimension cumulative_energy value
cumulative_energy skip in k dimension weather_description value
cumulative_energy skip in k dimension clouds_all value
cumulative_energy skip in k dimension temp_f value
cumulative_energy skip in k dimension rain_1h value
cumulative_energy skip in k dimension snow_1h value
cumulative_energy skip in k dimension hour value
cumulative_energy skip in k dimension day value
cumulative_energy skip in k dimension month value
weather_description skip in k dimension date_time value
weather_description skip in k dimension power_delivered value
weather_description skip in k dimension energy_delivered value
weather_description skip in k dimension cumulative_energy value
weather_description skip in k dimension weather_description value
weather_description skip in k dimension clouds_all value
weather_description skip in k dimension temp_f value
weather_description skip in k dimension rain_1h value
weather_description skip in k dimension snow_1h value
weather_description skip in k dimension hour value
weather_description skip in k dimension day value
weather_description skip in k dimension month value
clouds_all skip in k dimension date_time value
clouds_all skip in k dimension power_delivered value
clouds_all skip in k dimension energy_delivered value
clouds_all skip in k dimension cumulative_energy value
clouds_all skip in k dimension weather_description value
clouds_all skip in k dimension clouds_all value
clouds_all skip in k dimension temp_f value
clouds_all skip in k dimension rain_1h value
clouds_all skip in k dimension snow_1h value
clouds_all skip in k dimension hour value
clouds_all skip in k dimension day value
clouds_all skip in k dimension month value
temp_f skip in k dimension date_time value
temp_f skip in k dimension power_delivered value
temp_f skip in k dimension energy_delivered value
temp_f skip in k dimension cumulative_energy value
temp_f skip in k dimension weather_description value
temp_f skip in k dimension clouds_all value
temp_f skip in k dimension temp_f value
temp_f skip in k dimension rain_1h value
temp_f skip in k dimension snow_1h value
temp_f skip in k dimension hour value
temp_f skip in k dimension day value
temp_f skip in k dimension month value
rain_1h skip in k dimension date_time value
rain_1h skip in k dimension power_delivered value
rain_1h skip in k dimension energy_delivered value
rain_1h skip in k dimension cumulative_energy value
rain_1h skip in k dimension weather_description value
rain_1h skip in k dimension clouds_all value
rain_1h skip in k dimension temp_f value
rain_1h skip in k dimension rain_1h value
rain_1h skip in k dimension snow_1h value
rain_1h skip in k dimension hour value
rain_1h skip in k dimension day value
rain_1h skip in k dimension month value
snow_1h skip in k dimension date_time value
snow_1h skip in k dimension power_delivered value
snow_1h skip in k dimension energy_delivered value
snow_1h skip in k dimension cumulative_energy value
snow_1h skip in k dimension weather_description value
snow_1h skip in k dimension clouds_all value
snow_1h skip in k dimension temp_f value
snow_1h skip in k dimension rain_1h value
snow_1h skip in k dimension snow_1h value
snow_1h skip in k dimension hour value
snow_1h skip in k dimension day value
snow_1h skip in k dimension month value
hour skip in k dimension date_time value
hour skip in k dimension power_delivered value
hour skip in k dimension energy_delivered value
hour skip in k dimension cumulative_energy value
hour skip in k dimension weather_description value
hour skip in k dimension clouds_all value
hour skip in k dimension temp_f value
hour skip in k dimension rain_1h value
hour skip in k dimension snow_1h value
hour skip in k dimension hour value
hour skip in k dimension day value
hour skip in k dimension month value
day skip in k dimension date_time value
day skip in k dimension power_delivered value
day skip in k dimension energy_delivered value
day skip in k dimension cumulative_energy value
day skip in k dimension weather_description value
day skip in k dimension clouds_all value
day skip in k dimension temp_f value
day skip in k dimension rain_1h value
day skip in k dimension snow_1h value
day skip in k dimension hour value
day skip in k dimension day value
day skip in k dimension month value
month skip in k dimension date_time value
month skip in k dimension power_delivered value
month skip in k dimension energy_delivered value
month skip in k dimension cumulative_energy value
month skip in k dimension weather_description value
month skip in k dimension clouds_all value
month skip in k dimension temp_f value
month skip in k dimension rain_1h value
month skip in k dimension snow_1h value
month skip in k dimension hour value
month skip in k dimension day value
month skip in k dimension month value

In [8]:
# print(relationships)

In [9]:
# j = 0
# final = []
# for i in relationships:
#     current = i
# #     newlist = col
#     newlist = list(filter(lambda x: x != i, relationships))
# #     print(current)
# #     print(newlist)
# #     print(j)
#     j = j + 1
#     X = fiveaxis[newlist]
#     y = fiveaxis[current].values.reshape(-1,1)
#     X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
#     X_scaler = StandardScaler().fit(X_train)
#     y_scaler = StandardScaler().fit(y_train)
#     X_train_scaled = X_scaler.transform(X_train)
#     X_test_scaled = X_scaler.transform(X_test)
#     y_train_scaled = y_scaler.transform(y_train)
#     y_test_scaled = y_scaler.transform(y_test)
#     model = LinearRegression()
#     model.fit(X_train_scaled, y_train_scaled)
#     predictions = model.predict(X_test_scaled)
#     MSE = mean_squared_error(y_test_scaled, predictions)
#     r2 = model.score(X_test_scaled, y_test_scaled)
#     if MSE != 0 and r2 != 1.0:
#       if MSE <= .1 and r2 >= .85:
#         final.append(current)
#     print(f"{current}, MSE: {MSE}, R2: {r2}")
# print(final)

In [10]:
# import pandas as pd
# import requests
# import datetime as dt
# from pprint import pprint

In [11]:
# import pandas as pd
# import requests
# import datetime as dt
# from pprint import pprint
# url = "https://api.sunrise-sunset.org/json?lat=44.986656&lng=-93.258133&date="
# # date = dt.date.today()
# date = fiveaxis['date_time'][0]

# response = requests.get(f"{url}{date}").json()
# pprint(response['results'])
# pprint(response['results']['day_length'])
# pprint(response['results']['sunrise'])
# pprint(response['results']['sunset'])

In [12]:
# print(date)

In [13]:
# for i in fiveaxis['date_time']:
#     date = i
#     response = requests.get(f"{url}{date}").json()
#     daylength = response['results']['day_length'] 
#     print(daylength)
# #         fiveaxis = fiveaxis.append(daylength)
# #     #     fiveaxis = fiveaxis.append(pd.io.json.json_normalize(response['results']['sunrise']))
# #     #     fiveaxis = fiveaxis.append(pd.io.json.json_normalize(response['results']['sunset']))
# # fiveaxis.head()